language: php
sudo: false

php:
  - 7.3

before_script:
  - curl -LSs https://box-project.github.io/box2/installer.php | php
  - composer install --no-interaction --no-progress

script:
  - ./vendor/bin/phpcs
  - ./box.phar build
  - sha1sum blt.phar > blt.version

deploy:
  provider: releases
  # Needed per https://stackoverflow.com/questions/41133548/how-to-fix-github-release-deployment-of-latex-project.
  skip_cleanup: true
  api_key:
    secure: "sQHjArOs7rFfrgq6TRy1QZ8oEXBzV2HlEycu/hS2cdOqGTGW1sjV2Zk1Wvu6TXKV1ShF4UKdcl2KDiKNXXqayArIoUdxybp8tjKk4XmZdm5LalpjDDBo3emKpvnNlM3jZGhO6SP1uYBkXKvP0b88rqwd2ILVAUwevEfYNKKUnJSubpvJCDLs3vSfscsCfxqHYvnSdVxglzUY9upS1yArwM7J8mVLVI2sHL8S0VNjdYZB73FrnqxmvHIk4rvjMQnjV6/R/2faZV0hQM3K4+9UUYyLkdZlvzj7h/hGFRnJNnK+PkII8FKx82kaCjgZnImrix//AHfgzgN2/T7Bh9hoIQ3Tk/tNjmCK5f4l1hcq1aHckbObql5hAFcAk9qSVk+8o2mKhLK9vM5xAq8037hUwcjqfU0cOkQk5J6hjMzWQL7VEjDwEW9OlVjUugHVqUGo70fuxzyac9NPWLADuTyjo7azKDnxOfXqEL2TjUlZ39k/cDmofafMJ/FLrYB5al4O7CV2DzOUjw8BjoXvTGnWV1bwnKABxieCYhqLcgOd6vo/RcdU/SzTTvfOalI8OI8Iby7W5w5YwTl9FUS5gPmKfdrr9C/H5gFSajOzQbgZCFUQNMenM6c2GXoddREWk4KKQEHopcxAbkUab+h2lhp5F+bwnBtsxzS/yHZABVncy88="
  file:
    - blt.phar
    - blt.version
  on:
    repo: acquia/blt-launcher
    tags: true
