language: php
sudo: false

php:
  - 7.3

before_script:
  - curl -LSs https://box-project.github.io/box2/installer.php | php
  - composer install --no-interaction --no-progress

script:
  - ./vendor/bin/phpcs
  - ./box.phar build
  - sha1sum blt.phar > blt.version

deploy:
  provider: releases
  # Needed per https://stackoverflow.com/questions/41133548/how-to-fix-github-release-deployment-of-latex-project.
  skip_cleanup: true
  api_key:
    secure: DbvzBB1nnO70gCFLT78i8lxhOABuVIEAKUYAwJQsRxoyoPCyMsGHhmrCMAYb2mGa1zxZh7/S4FXmDKBteOIctcA6QkLzDF6fcVO9w83cC79k915GNGSbv/ztUfMa2kVzfYf9RikXMOhQ9OADF/fDMuy9Ut5jwKj1/r0IPhYHJmA/g8bLzgWf6KkpCXUPlXxXnB/+xFd7+bQHTBpd+6Zb9GDPZjpjYrjuyset9A1RYwPw01HPejL/3gJ3Cj02f2cvd+eTwaASCpmFDk+Cn7dPRtIvNVCx7zsgPbnzw7TkSoCOZKLLvmqLMPlSYj48gJdCvdCFmQcbTm2SCU5n4z2TOGN5qCrYG73574LOvpyo6FebdoahxvZdPBdHbxpyaeiXoOLuASiyPHfSLmT0nMGVo/AIv6b9xSTc4YzMLsDovJ6YKXl9KzZTf1KPoMjAQCKrPMfE2R5h1wFP5Fc29BnPXn3hW1QUt8kXq6U6tADVtwK5yEsDp+9ZdxUDgPA0wMcAAsPzDqTUg1uvEzacfi9TtgqXxbVGLX8KXBszZC0qL7PhDQexuKdYjlM7qkVcF5OOl6qQ3+IjIAEx1J8oK0vonfBR3/nw3As6E4EUpF+ZJ62EtfQ037U9/rkjVJ2wQlhX3B5OdHlZU6NggNvMYzDGw0OMCQfLLzyJgdW9n8lOH2k=
  file:
    - blt.phar
    - blt.version
  on:
    repo: acquia/blt-launcher
    tags: true
