language: php
sudo: false

php:
  - 7.3

before_script:
  - composer box-install
  - composer install --no-interaction --no-progress

script:
  - ./vendor/bin/phpcs
  - composer box-compile
  - sha1sum blt.phar > blt.version

deploy:
  provider: releases
  # Needed per https://stackoverflow.com/questions/41133548/how-to-fix-github-release-deployment-of-latex-project.
  skip_cleanup: true
  api_key:
    secure: "mTqb9Ib0fhm5twg9X1mtnX98cjLpArdWRIgtDYoYGKc5wfU8hmxlJjT7KYescfs/XfCm8Xp0WjjT4peWtTt1yl3StpcJAb47reUI7npDf2N5nvGXbxXe0yteme/ZmdCvuMfD3bbjKKOamxxFWzoKVj/9m/F5jzdfhfVIvy8qZiMV0CTNXnuaaPbrga+TYtgPkM6juQ53XH3PkQ6+rz2FDG1GA9W8/vGJtI2JrnV46jEfR8LTD8kl4byvnHKhLMns60WP1vZaCS+zogBtQtYMLQXOIJH4aXebBq2+MhJUNhzRfsQsfpQioIkZKY0jSFFobkkZT61Az+zJFdAm1MBe+lGzTjlNJJ4IGxO6RGc8MMUFmopBO4dzk7ZjIKqQ58YN+6QQW3w2TuSPrUuMVSVbRAskucGRpDUlHrocfD6qJ0QEUyBE6vNQSewXfwNX0NiiHlHGnz69w8bdnE0cD05/VFBFQGNluYhXbnTTEmert7PP9JuFI2pqy1UJ4K3EhU1sF5HeGmsXprADcIuWNpVp67ltRPt+HUbOLa7M3xqgMvFSa+VnMQ1RWaOOgDEkXGX2PFzgYrMxQHFLPxulOWMk8RwKXZvlCJZ5BZpjvYeRhO4rEIKx/BXc8Y+kZGsdOkypl0lYWlHPdtXE2ArdTgRoJWWq5mAMgEbdCgLIfxyPrgk="
  file:
    - blt.phar
    - blt.version
  on:
    repo: acquia/blt-launcher
    tags: true
